<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="2" skipped="0" tests="3" time="0.113"
               timestamp="2022-05-31T20:13:55.816901" hostname="MinhNhan">
        <testcase classname="test_1" name="test_greater" time="0.001">
            <failure message="assert 50 &gt; 100">input_value = 50

                @pytest.mark.great
                def test_greater(input_value):
                &gt; assert input_value &gt; 100
                E assert 50 &gt; 100

                test_1.py:7: AssertionError
            </failure>
        </testcase>
        <testcase classname="test_1" name="test_greater_equal" time="0.001">
            <failure message="assert 50 &gt;= 100">input_value = 50

                @pytest.mark.great
                def test_greater_equal(input_value):
                &gt; assert input_value &gt;= 100
                E assert 50 &gt;= 100

                test_1.py:13: AssertionError
            </failure>
        </testcase>
        <testcase classname="test_1" name="test_less" time="0.001"/>
    </testsuite>
</testsuites>